apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    production: ready
spec:
  replicas: 1
  selector:
    matchLabels:
      production: ready
  template:
    metadata:
      labels:
        production: ready
    spec:
      volumes:
      - name: web-dir
        empty-dir: {}
      initContainers:
      - name: populate-web-dir
        image: quay.io/karmab/curl:latest
        command:
        - "/bin/sh"
        - "-c"
        - |
          #/bin/sh
          echo "MESSAGE I am a container" > /usr/local/apache2/htdocs/index.html
        volumeMounts:
          - name: web-dir
            mountPath: "/usr/local/apache2/htdocs"
      containers:
        - name: httpd
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
          image: docker.io/httpd:2.4
          ports:
          - containerPort: 80
          volumeMounts:
           - name: web-dir
             mountPath: "/usr/local/apache2/htdocs"
---
apiVersion: v1
kind: Service
metadata:
  name: production-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    production: ready
  sessionAffinity: None
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    production: ready
  name: production-web
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: production-web
  wildcardPolicy: None
