apiVersion: v1
kind: Service
metadata:
  name: production-1-ssh-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: production-1
    kubevirt.io/provider: kcli
  sessionAffinity: None
  type: NodePort
